/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import identidades.Country;
import repository.CountryRepositoryFile;
import repository.CountryRepository;
import repository.CountryRepositoryDb;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import service.SlugService;
import service.SlugServiceImp;


/**
 *
 * @author Emilio
 */
public class CountryForm extends javax.swing.JFrame{
    private SlugService slugservice = new SlugServiceImp();
    private CountryRepository repositoryFile = new CountryRepositoryFile(slugservice);
    private CountryRepository repositoryDb = new CountryRepositoryDb(slugservice);
    /**
     * Creates new form CountryForm
     */
    public CountryForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSeleccion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCountryName = new javax.swing.JTextField();
        txtCountryId = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        btFindCountry = new javax.swing.JButton();
        txtCountrySlug = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCountries = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblSlug = new javax.swing.JLabel();
        btFillList = new javax.swing.JButton();
        rbFile = new javax.swing.JRadioButton();
        rbDataBase = new javax.swing.JRadioButton();
        btClean = new javax.swing.JButton();
        chbFind = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COUNTRIES - SDME");

        jLabel1.setText("COUNTRY");

        jLabel2.setText("NAME:");

        jLabel3.setText("ID:");

        txtCountryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCountryNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCountryNameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCountryNameKeyTyped(evt);
            }
        });

        txtCountryId.setEnabled(false);

        btSave.setText("INGRESAR");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        btFindCountry.setText("...");
        btFindCountry.setEnabled(false);
        btFindCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindCountryActionPerformed(evt);
            }
        });

        txtCountrySlug.setEnabled(false);

        jLabel4.setText("SLUG");

        lstCountries.setBorder(javax.swing.BorderFactory.createTitledBorder("COUNTRIES"));
        lstCountries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCountriesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCountries);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("COUNTRY INFORMATION"));

        jLabel5.setText("ID:");

        jLabel6.setText("NAME:");

        jLabel7.setText("SLUG:");

        lblId.setText(" ");

        lblName.setText(" ");

        lblSlug.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(lblSlug, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSlug))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btFillList.setText("LLENAR LISTA");
        btFillList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFillListActionPerformed(evt);
            }
        });

        bgSeleccion.add(rbFile);
        rbFile.setText("FILE");

        bgSeleccion.add(rbDataBase);
        rbDataBase.setText("DATA BASE");

        btClean.setText("LIMPIAR");
        btClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCleanActionPerformed(evt);
            }
        });

        chbFind.setText("HABILITAR CONSULTA");
        chbFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCountryId, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btFindCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCountrySlug, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(rbFile)
                        .addGap(40, 40, 40)
                        .addComponent(rbDataBase))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(chbFind)
                        .addGap(41, 41, 41)
                        .addComponent(btSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btFillList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCountryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btFindCountry)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCountrySlug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbFind)
                            .addComponent(btSave)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btFillList)
                        .addGap(35, 35, 35)
                        .addComponent(btClean))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbFile)
                            .addComponent(rbDataBase))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if(rbFile.isSelected()){
            save(repositoryFile);
        }
        else{
            if(rbDataBase.isSelected()){
                save(repositoryDb);
            }
            else{
                JOptionPane.showMessageDialog(null,"PORFAVOR SELECCIONE UNA OPCION","WARNING",JOptionPane.ERROR_MESSAGE);
            }
        }
        clean();
    }//GEN-LAST:event_btSaveActionPerformed

    private void btFindCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindCountryActionPerformed
        if(rbFile.isSelected()){
            findCountry(repositoryFile);
        }
        else{
            if(rbDataBase.isSelected()){
                findCountry(repositoryDb);
            }
            else{
                JOptionPane.showMessageDialog(null,"PORFAVOR SELECCIONE UNA OPCION","WARNING",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btFindCountryActionPerformed

    private void btFillListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFillListActionPerformed
        if(rbFile.isSelected()){
            findAllCountries(repositoryFile);
        }
        else{
            if(rbDataBase.isSelected()){
                findAllCountries(repositoryDb);
            }
            else{
                JOptionPane.showMessageDialog(null,"PORFAVOR SELECCIONE UNA OPCION","WARNING",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btFillListActionPerformed

    private void lstCountriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCountriesMouseClicked
        fillInformation();
    }//GEN-LAST:event_lstCountriesMouseClicked

    private void btCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCleanActionPerformed
        cleanList();
    }//GEN-LAST:event_btCleanActionPerformed

    private void chbFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFindActionPerformed
        if(chbFind.isSelected()){
            btFindCountry.setEnabled(true);
            txtCountryId.setEnabled(true); 
        }
        else{
            btFindCountry.setEnabled(false);
            txtCountryId.setEnabled(false);
        }
    }//GEN-LAST:event_chbFindActionPerformed

    private void txtCountryNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryNameKeyTyped
        
    }//GEN-LAST:event_txtCountryNameKeyTyped

    private void txtCountryNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryNameKeyPressed
        
    }//GEN-LAST:event_txtCountryNameKeyPressed

    private void txtCountryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCountryNameKeyReleased
        txtCountrySlug.setText(slugservice.getWord(txtCountryName.getText()));
    }//GEN-LAST:event_txtCountryNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountryForm().setVisible(true);
            }
        });
    }
    /*
    public void generarDoc(){
        File file = new File("D:\\Docs U\\4to Semestre\\Programacion III\\Taller\\countries.txt");
        repository.setArchivo(file);
        List<String> countries = repository.readCountry();
        for(String name : countries){
            Country country = new Country(repository.getCountryLastId()+1,name,repository.getWord(name));
            repository.save(country);
        }
        
    }
    */
    
    private void save(CountryRepository repository){
        Country country = new Country(repository.getCountryLastId()+1,txtCountryName.getText(),txtCountrySlug.getText());
        repository.save(country);
    }
    
    private void clean(){
        txtCountryName.setText("");
        txtCountryId.setText("");
        lblId.setText("");
        lblName.setText("");
        lblSlug.setText("");
        txtCountrySlug.setText("");
        txtCountryId.setText("");
    }
    
    private void findCountry(CountryRepository repository){
        Country country = repository.getCountry(Integer.parseInt(txtCountryId.getText()));
        if(country != null){
            txtCountryId.setText(Integer.toString(country.getCountryId()));
            txtCountryName.setText(country.getCountryName());
            txtCountrySlug.setText(country.getCountrySlug());
        }
    }
    
    private void findAllCountries(CountryRepository repository){
        List<Country> countries = repository.getCountries();
        DefaultListModel dlmLista = new DefaultListModel();
        for(Country country : countries){
            dlmLista.addElement(country);
        }
        lstCountries.setModel(dlmLista);
    }
    
    private void fillInformation(){
        Country country = (Country)lstCountries.getSelectedValue();
        if(country != null || lstCountries.getSelectedIndex() != -1){
            lblId.setText(Integer.toString(country.getCountryId()));
            lblName.setText(country.getCountryName());
            lblSlug.setText(country.getCountrySlug());
        }
    }
    
    private void cleanList(){
        lstCountries.setModel(new DefaultListModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSeleccion;
    private javax.swing.JButton btClean;
    private javax.swing.JButton btFillList;
    private javax.swing.JButton btFindCountry;
    private javax.swing.JButton btSave;
    private javax.swing.JCheckBox chbFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSlug;
    private javax.swing.JList lstCountries;
    private javax.swing.JRadioButton rbDataBase;
    private javax.swing.JRadioButton rbFile;
    private javax.swing.JTextField txtCountryId;
    private javax.swing.JTextField txtCountryName;
    private javax.swing.JTextField txtCountrySlug;
    // End of variables declaration//GEN-END:variables
}
